<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>48f64ff4-9c44-47d6-90e0-928c37f8eca1</elementGuidId>
    <imagePath></imagePath>
    <name>button_react-burger-menu-btn</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#react-burger-menu-btn</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'react-burger-menu-btn') and equals(@text,'Open Menu')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>react-burger-menu-btn</value>
        <webElementGuid>d64acc40-43a1-4960-996b-c23d26ff0b35</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Open Menu</value>
        <webElementGuid>d64acc40-43a1-4960-996b-c23d26ff0b35</webElementGuid>
    </webElementProperties>
</WebElementEntity>