<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>aa7a7978-0ac8-4b06-b042-32fc1c8417e6</elementGuidId>
    <imagePath></imagePath>
    <name>button_react-burger-menu-btn</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#react-burger-menu-btn</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'react-burger-menu-btn') and equals(@text,'Open Menu')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>react-burger-menu-btn</value>
        <webElementGuid>a1fe1b3c-d5fe-4d28-a96e-88543459da6a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Open Menu</value>
        <webElementGuid>a1fe1b3c-d5fe-4d28-a96e-88543459da6a</webElementGuid>
    </webElementProperties>
</WebElementEntity>