<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1cdc6344-cfee-4095-abe2-9e69f1f744ad</elementGuidId>
    <imagePath></imagePath>
    <name>link_item_3_title_link</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[6]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#item_3_title_link</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'item_3_title_link') and equals(@text,'Test.allTheThings() T-Shirt (Red)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>item_3_title_link</value>
        <webElementGuid>a1fe1b3c-d5fe-4d28-a96e-88543459da6a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Test.allTheThings() T-Shirt (Red)</value>
        <webElementGuid>a1fe1b3c-d5fe-4d28-a96e-88543459da6a</webElementGuid>
    </webElementProperties>
</WebElementEntity>