<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>46a66f3a-3978-4541-a274-bf3f2c203d38</elementGuidId>
    <imagePath></imagePath>
    <name>link_inventory_sidebar_link</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/nav[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#inventory_sidebar_link</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'inventory_sidebar_link') and equals(@text,'All Items')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>inventory_sidebar_link</value>
        <webElementGuid>b918e3d4-7815-497c-9189-5f26ffe08ac0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>All Items</value>
        <webElementGuid>b918e3d4-7815-497c-9189-5f26ffe08ac0</webElementGuid>
    </webElementProperties>
</WebElementEntity>