<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6ac55b6e-5084-4755-91e2-fbf44052b672</elementGuidId>
    <imagePath></imagePath>
    <name>link_item_0_title_link</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#item_0_title_link</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'item_0_title_link') and equals(@text,'Sauce Labs Bike Light')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>item_0_title_link</value>
        <webElementGuid>b918e3d4-7815-497c-9189-5f26ffe08ac0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sauce Labs Bike Light</value>
        <webElementGuid>b918e3d4-7815-497c-9189-5f26ffe08ac0</webElementGuid>
    </webElementProperties>
</WebElementEntity>