<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4c914716-71df-4023-8645-a66cb6359921</elementGuidId>
    <imagePath></imagePath>
    <name>link_item_1_title_link</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#item_1_title_link</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'item_1_title_link') and equals(@text,'Sauce Labs Bolt T-Shirt')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>item_1_title_link</value>
        <webElementGuid>a1fe1b3c-d5fe-4d28-a96e-88543459da6a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sauce Labs Bolt T-Shirt</value>
        <webElementGuid>a1fe1b3c-d5fe-4d28-a96e-88543459da6a</webElementGuid>
    </webElementProperties>
</WebElementEntity>