<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>09451856-835a-49bb-a6eb-e468bbf73255</elementGuidId>
    <imagePath></imagePath>
    <name>link_inventory_sidebar_link</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/nav[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#inventory_sidebar_link</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'inventory_sidebar_link') and equals(@text,'All Items')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>inventory_sidebar_link</value>
        <webElementGuid>a1fe1b3c-d5fe-4d28-a96e-88543459da6a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>All Items</value>
        <webElementGuid>a1fe1b3c-d5fe-4d28-a96e-88543459da6a</webElementGuid>
    </webElementProperties>
</WebElementEntity>